name: Build

on:
  push: {branches: main}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: {node-version: '12'}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Push new build
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git fetch origin release
          git checkout release
          build_source=$(git rev-parse HEAD)
          git diff HEAD..main ':^.gitignore' ':^dist' | git apply
          npm run build
          git add --all
          git commit -m "Build from $build_source\n\nThis build was generated in this workflow run:\nhttps://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          git push origin release
