name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v2
      - run: actions/setup-node@v1
        with: {node-version: '12'}
      - run: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: |
          git fetch origin release
          git checkout release
          git merge main
          npm run build
          git add dist
          git commit -m 'Build from https://github.com/${{ GITHUB_REPOSITORY }}/actions/runs/${{ GITHUB_RUN_ID }}'
          git push origin release
